version: "3.9"
   
services:
  app:
    build: ./app
    command: django-admin runserver 0.0.0.0:8000
    env_file: ./app/.env.development
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true